# Generated by Django 6.0.2 on 2026-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('period', models.CharField(help_text='Напр: Sep 2019 - July 2023', max_length=50, verbose_name='Період')),
                ('description', models.TextField(blank=True, verbose_name="Опис обов'язків")),
                ('order', models.IntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Досвід роботи',
                'verbose_name_plural': 'Досвід роботи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Я Влад', max_length=100, verbose_name="Ім'я та Прізвище")),
                ('role', models.CharField(default='графічний дизайнер', max_length=100, verbose_name='Посада (хедер)')),
                ('photo', models.ImageField(upload_to='profile/', verbose_name='Фото профілю')),
                ('about_text', models.TextField(verbose_name="Текст 'Про себе'")),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('behance', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Профіль власника',
                'verbose_name_plural': 'Профіль власника',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва послуги')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Картинка картки')),
                ('link', models.URLField(blank=True, verbose_name='Посилання (опціонально)')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва скіла')),
                ('icon', models.ImageField(upload_to='skills/', verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Навичка (Skill)',
                'verbose_name_plural': 'Навички',
            },
        ),
    ]
