# Generated by Django 6.0.2 on 2026-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Instagram, LinkedIn', max_length=50, verbose_name='Network Name')),
                ('icon', models.FileField(help_text='SVG or PNG format recommended', upload_to='socials/', verbose_name='Icon')),
                ('link', models.URLField(verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'verbose_name': 'Owner Profile', 'verbose_name_plural': 'Owner Profiles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='instagram',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='emoji_bottom_left',
            field=models.CharField(default='💡', help_text='Floating emoji bottom-left.', max_length=10, verbose_name='Deco Emoji 2 (Bottom Left)'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='emoji_main',
            field=models.CharField(default='👋', help_text='The large emoji in the center.', max_length=10, verbose_name='Main Emoji (Big)'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='emoji_top_left',
            field=models.CharField(default='⚡', help_text='Floating emoji top-left.', max_length=10, verbose_name='Deco Emoji 3 (Top Left)'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='emoji_top_right',
            field=models.CharField(default='👋', help_text='Floating emoji top-right.', max_length=10, verbose_name='Deco Emoji 1 (Top Right)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.CharField(help_text='e.g. Sep 2019 - July 2023', max_length=50, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='about_text',
            field=models.TextField(default='Description about me...', verbose_name='About Me Text'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='name',
            field=models.CharField(default='Vlad', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='role',
            field=models.CharField(default='Graphic Designer', max_length=100, verbose_name='Role (Header)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Card Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link (Optional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Service Title'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='skills/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Skill Name'),
        ),
    ]
